// GENERATED by `task docs:accept` — DO NOT EDIT.
// Source of truth: each module def's co-located `docs` field. The prerendered
// doc page imports this because it cannot import the live registry. Freshness is
// gated by contract-lock.test.ts (a stale copy fails CI).
import type { ModuleDocs } from '$lib/graph/types';

export const MODULE_DOCS: Record<string, ModuleDocs> = {
  "adsr": {
    "explanation": "A classic gate-driven envelope generator: a held gate runs the level up to peak over the attack time, falls to the sustain level over the decay time, holds there for as long as the gate stays high, then falls back to zero over the release time when the gate drops. It outputs a unipolar 0..1 control signal (env) plus its inverse (env_inv = 1 - env) for ducking; patch it into any CV input (a VCA's gain, a filter's cutoff) to shape that destination over the life of each note.",
    "inputs": {
      "attack": "CV that modulates the attack-time fader: a -1..+1 signal sweeps the attack symmetrically in log time around your fader setting (±1 multiplies/divides the time by 100x), so an LFO here covers two log decades of attack speed centered on the knob (clamped to the 1 ms..10 s range).",
      "decay": "CV that modulates the decay-time fader the same way — a -1..+1 signal scales decay symmetrically in log time (±1 = 100x faster/slower) around your fader setting, clamped to 1 ms..10 s.",
      "gate": "The note signal that drives the whole envelope: a rising edge (gate goes high) starts the attack stage, then it decays to and holds at the sustain level WHILE the gate stays high (this input is level-sensitive, not just edge-triggered), and the falling edge (gate goes low) starts the release stage back to 0. Re-gating is a hard retrigger — a new rising edge snaps the output back to 0 and ramps the attack again from zero, it does NOT continue from the level it was at.",
      "release": "CV that modulates the release-time fader — a -1..+1 signal scales release symmetrically in log time (±1 = 100x faster/slower) around your fader setting, clamped to 1 ms..10 s.",
      "sustain": "CV that displaces the sustain level — linear, since the param is already a native 0..1 level, so the signal pushes the held level up or down by up to half the range around your fader setting (clamped to 0..1)."
    },
    "outputs": {
      "env": "The envelope itself as a unipolar 0..1 control signal — 0 at rest, ramping to 1 at the attack peak, holding at the sustain level while gated, then falling to 0 on release. Patch into a VCA gain, filter cutoff, or any CV destination to shape it over each note.",
      "env_inv": "The inverted envelope, 1 - env: it sits at 1 at rest and dips toward 0 as the envelope rises (full env peak = 0 out). Patch into a VCA or filter to duck / reverse-modulate that destination on every note, sidechain-style."
    },
    "controls": {
      "attack": "How long the envelope takes to rise from 0 to its peak (1.0) after the gate goes high — 1 ms at the bottom up to 10 s at the top, on a log fader so most of the travel lives in the short, snappy times.",
      "decay": "How long the envelope takes to fall from the peak down to the sustain level once the attack finishes — 1 ms to 10 s, log fader. Has no audible effect if sustain is already at 1.0 (nothing to decay to).",
      "release": "How long the envelope takes to fall from wherever it currently is back to 0 once the gate goes low — 1 ms to 10 s, log fader.",
      "sustain": "The level the envelope holds at for as long as the gate stays high, after attack and decay complete — 0 (no sustain, decays all the way to silence) up to 1.0 (holds at full peak); linear fader."
    }
  },
  "blood": {
    "explanation": "BLOOD runs the NBlood (Build-engine) port of Blood as an interactive video source. It is owner-only and single-instance — the rack owner spawns it and plays; the video output is the Build software-rendered framebuffer, letterboxed into the engine canvas. Game data (BLOOD.RFF / GUI.RFF / SOUNDS.RFF / TILES000.ART) is USER-SUPPLIED and not redistributable, so the card shows a \"data missing\" overlay until you run `task setup:blood` with a copy you own (GOG/Steam One Unit Whole Blood or Fresh Supply).",
    "inputs": {
      "altfire": "CV gate — alternate fire while held HIGH.",
      "crouch": "CV gate — stay crouched while held HIGH.",
      "down": "CV gate — move backward while held HIGH.",
      "enter": "CV trigger — confirm the highlighted menu item (fires once per rising edge).",
      "esc": "CV trigger — open / back out of the menu (fires once per rising edge).",
      "fire": "CV gate — fire the current weapon while the gate is held HIGH.",
      "jump": "CV gate — jump while held HIGH.",
      "left": "CV gate — turn left while held HIGH.",
      "right": "CV gate — turn right while held HIGH.",
      "up": "CV gate — move forward while the gate is held HIGH.",
      "use": "CV gate — open doors / use switches while held HIGH.",
      "weapnext": "CV gate — select the next weapon while held HIGH.",
      "weapprev": "CV gate — select the previous weapon while held HIGH."
    },
    "outputs": {
      "audio_l": "Left channel of the game audio (silent in v1 — PCM bridge is stubbed).",
      "audio_r": "Right channel of the game audio (silent in v1 — PCM bridge is stubbed).",
      "out": "The Build software-rendered game framebuffer, aspect-correct letterboxed into the canvas."
    },
    "controls": {
      "audioGain": "Trims the game-audio level feeding audio_l/audio_r (0..2, default 1).",
      "fillMode": "Letterbox (preserve aspect, default) vs fill (cover-crop) the canvas."
    }
  },
  "cocoadelay": {
    "explanation": "A tape-style stereo delay (clean-room port of Tilde Murray's Cocoa Delay): audio is written into a 10-second stereo tape buffer and read back at a fractional, modulated position with 4-point Hermite interpolation. The read time is the base delay (free-running TIME, or a musical division of a clock beat when SYNC is on), warped per-sample by an LFO and a slow random DRIFT, with bipolar feedback feeding the echoes back through an in-loop multi-mode FILTER and saturating DRIVE; PAN modes spread the wet image, DUCKING sidechains the wet level off the dry input, and DRY/WET set the final mix. Mental model: think of it as one tape echo where almost every knob can also be voltage-controlled, and where a patched CLK pulse or the rack/MIDI tempo can lock the delay to the beat.",
    "inputs": {
      "clock": "External clock/gate: when SYNC is on, the delay measures the period between rising edges (level crossing up through ~0.5) of pulses here and locks the delay time to that period times the chosen division — it takes two rising edges to establish a period, so the lock engages on the second pulse. A patched clock ALWAYS wins over both the rack SYSTEM tempo and MIDI clock; when SYNC is Off this input has no audible effect and TIME is free-running.",
      "drift_cv": "CV modulation of DRIFT AMOUNT (driftAmount, linear), the depth of the slow random tape-drift walk applied to the read time. More CV = more wow/flutter wander.",
      "drive_cv": "CV modulation of the in-loop saturation amount (targets driveGain, linear). Raises or lowers how hard the feedback path is driven into the stateful saturator per-sample.",
      "duck_cv": "CV modulation of DUCK AMOUNT (duckAmount, linear) — how strongly the wet level is pulled down by the envelope follower riding the dry input. More CV = the echoes get out of the way harder when dry signal is present.",
      "feedback_cv": "CV modulation of FEEDBACK, summed into the knob (linear). Pushes the regeneration amount up or down per-sample; since feedback is bipolar (-1..+1), negative-direction CV can flip the feedback polarity.",
      "inL": "Left audio into the delay — together with inR this is the dry signal that gets written to tape, tapped through the wet path, and summed back into the output.",
      "inR": "Right audio into the delay; it is an independent channel, NOT normaled to inL — if you patch only inL the right side stays silent (a mono source feeds both channels only if you patch both inL and inR, e.g. via the module's stereo auto-wire).",
      "lfo_cv": "CV modulation of the LFO AMOUNT (lfoAmount, linear) — i.e. the depth with which the internal time LFO wobbles the delay read position. It does not change the LFO rate, only how much it warps the time.",
      "mix_cv": "CV modulation of the WET output level (targets wetVolume, linear). Use it to fade the echoes in and out under control voltage; the dry level is unaffected.",
      "pan_cv": "CV modulation of the PAN angle (pan, linear). Its audible effect depends on PAN MODE — it rotates the static placement, biases the ping-pong, or drives the circular wet-image rotation.",
      "time_cv": "CV modulation of the TIME knob (delayTime), summed into it with a log-scaled response so a -1..+1 CV sweeps the base delay across its full log range; sweeping it gives classic tape pitch-bend / smear on the echoes."
    },
    "outputs": {
      "outL": "Left of the stereo output: dry × DRY level + ducked wet × WET level, the left half of the combined dry+echo signal.",
      "outR": "Right of the stereo output: dry × DRY level + ducked wet × WET level, the right half of the combined dry+echo signal."
    },
    "controls": {
      "clockSource": "CLK SRC — picks which tempo reference SYNC follows when no clock cable is patched: SYSTEM reads the rack's TIMELORDE BPM, MIDI follows incoming MIDI clock (0xF8). Selecting MIDI is what first requests browser MIDI access; SYSTEM never prompts. A patched CLK input overrides either.",
      "delayTime": "TIME — the base delay length in seconds (0.001–2.0 s, log). Used directly when SYNC is Off; when SYNC is on it is only the fallback if no clock/tempo is available. LFO, DRIFT and STEREO offset all warp this value before the tape is read.",
      "driftAmount": "DRIFT AMOUNT — depth of a slow random walk on the delay time (0–0.05), the tape wow/flutter character. Higher = more wandering, less stable pitch on the echoes.",
      "driftSpeed": "DRIFT SPEED — how quickly the random drift walk moves (0.1–10, log). Faster speeds give jittery flutter, slower give long lazy pitch drift.",
      "driveCutoff": "DRIVE FILTER — post-saturator low-pass cutoff (0.01–1.0, normalized; default 1.0 = open) that tames the harshness the drive adds.",
      "driveGain": "DRIVE GAIN — how hard the feedback path is pushed into the stateful saturator (0–10). 0 bypasses drive entirely; higher adds progressively dirtier saturation that builds up over repeats.",
      "driveIterations": "DRIVE ITERATIONS — how many times the saturate-then-filter stage is run in series per sample (1–16). More iterations stack more saturation and filtering for a thicker, more compressed drive.",
      "driveMix": "DRIVE MIX — wet/dry blend across the saturator (0–1), how much of the saturated signal replaces the clean one inside the loop.",
      "dryVolume": "DRY — level of the unprocessed input passed straight to the output (0–2.0, default 1.0). Set to 0 for a fully wet send/return.",
      "duckAmount": "DUCK AMOUNT — how strongly the wet level is ducked by an envelope follower on the dry input sum (0–10). At 0 there is no ducking; higher values make the echoes recede whenever dry signal is playing.",
      "duckAttack": "DUCK ATTACK — how fast the ducking envelope clamps the wet down when dry signal arrives (0.1–100, log).",
      "duckRelease": "DUCK RELEASE — how fast the wet level recovers after the dry signal falls away (0.1–100, log).",
      "feedback": "FEEDBACK — bipolar regeneration amount (-1..+1, default 0.5). Higher magnitude = more/longer repeats; negative values invert the polarity of each fed-back repeat for a hollower tone.",
      "filterMode": "FILTER MODE — the topology of the in-feedback-loop tone filter: 1-pole, 2-pole, 4-pole, or State-variable. Steeper poles color the repeats more; changing mode crossfades smoothly.",
      "highCut": "HIGH CUT — the in-loop high-pass cutoff applied to each repeat (0.001–0.99, normalized; default 0.001 ≈ off). Raising it thins out the lows of successive echoes. (Label/role: this is the HP stage in the loop.)",
      "lfoAmount": "LFO AMOUNT — depth of the internal sine LFO that warps the delay read time (0–0.5). At 0 the LFO does nothing; higher values give pitch wobble / chorus-like movement on the echoes.",
      "lfoFrequency": "LFO FREQUENCY — rate of the time-warp LFO (0.1–10 Hz, log). Sets how fast the delay-time wobble cycles.",
      "lowCut": "LOW CUT — the in-loop low-pass cutoff applied to each repeat (0.01–1.0, normalized; default 0.75). Lower values darken successive echoes as they regenerate. (Despite the 'low cut' label it is the LP stage in the loop.)",
      "pan": "PAN — wet-image rotation angle (-π/2..+π/2). What it does depends on PAN MODE: static placement, ping-pong bias, or the amount of circular rotation applied to the wet signal.",
      "panMode": "PAN MODE — Static (a fixed rotation by PAN), Ping-Pong (swaps L/R as it writes to tape so repeats bounce side to side), or Circular (continuously rotates the wet stereo image). Switching modes crossfades to avoid clicks.",
      "stereoOffset": "STEREO — skews the left and right read times apart (-0.5..+0.5) by exponentiating the delay time oppositely per channel, widening the stereo image of the echoes. 0 keeps both channels at the same delay.",
      "syncPeriod": "Internal, not on the card: the seconds-per-beat the main thread bridges in for the selected CLK SRC (SYSTEM/MIDI), since the audio worklet can't read those sources directly. 0 means none available, in which case it falls back to the free-running TIME.",
      "tempoSync": "SYNC — Off (index 0) means TIME is free-running; any other setting locks the delay to a musical division of one beat (1, dotted/triplet variants… down to 1/64T). The beat comes from a patched clock pulse, else the chosen CLK SRC tempo.",
      "wetVolume": "WET — level of the delayed/echo signal in the output (0–2.0, default 0.5), the amount ducking pulls down and what mix_cv modulates."
    }
  },
  "fader": {
    "explanation": "A two-source video mixer with a built-in send/return FX loop, made of two stacked crossfaders. The first fader crossfades IN A and IN B into a mix that is also copied out the SEND jack (patch it through external video FX and return it); the second fader then blends that dry mix against the wet RETURN into the main OUT. Each fader has its own transition-shape dropdown so the crossfade can be a uniform fade or a wipe/dissolve/star/checkerboard sweep, and the whole thing renders as two GPU passes (pass 1 = A/B mix = SEND, pass 2 = dry/wet = OUT).",
    "inputs": {
      "in_a": "The A video source — what shows when the A/B fader is at 0. Left unpatched it reads as opaque black, so an unpatched A with the fader toward A gives a black frame.",
      "in_b": "The B video source — what shows when the A/B fader is at 1. Left unpatched it reads as opaque black.",
      "return": "The wet RETURN of the send/return loop: bring the processed video back in here after sending the A/B mix out SEND through external FX. It becomes the wet side of the dry/wet fader. Unpatched it reads as opaque black, so raising DRY/WET toward WET with nothing returned fades to black."
    },
    "outputs": {
      "out": "The main mix output: the dry A/B mix blended against the wet RETURN by the dry/wet fader and its transition shape (the second render pass, the module's canonical surface). With nothing patched into any input this is black.",
      "send": "A pre-FX copy of the A/B mix (the first render pass, taken before the dry/wet stage): patch this out to an external video FX chain and bring the result back into RETURN to build a send/return loop. Reflects only the A/B fader and its transition shape; with no A/B sources patched it is black."
    },
    "controls": {
      "abTransition": "Picks the SHAPE of the A→B crossfade as the fader moves: 0 fade (uniform dissolve across the whole frame), 1 wipe (a soft vertical edge sweeping left→right), 2 dissolve (a fixed random per-cell reveal that fills in more B as the fader rises), 3 star (a 5-point star iris of B growing from the centre outward), 4 checkerboard (even cells switch over during the first half of the fader travel, odd cells during the second). The stored value is rounded and clamped to 0..4, so anything out of range snaps to the nearest valid shape; at the very ends (fader fully A or fully B) every shape collapses to a clean A or B regardless of the dropdown.",
      "dryWet": "The dry↔wet blend that produces the final OUT: 0 shows only the dry A/B mix, 1 shows only the wet signal coming back into RETURN, with the in-between shaped by the D/W FX dropdown. Defaults to 0 (fully dry), so the send/return loop has no effect until you raise it. Clamped to 0..1, letting you fade an external effect in and out or transition into it with a wipe/dissolve.",
      "dwTransition": "Picks the SHAPE of the dry→wet blend, the same five options as the A/B shape: 0 fade, 1 wipe (left→right), 2 dissolve (per-cell random), 3 star iris, 4 checkerboard. Rounded and clamped to 0..4. Lets you transition into the returned/processed image with a hard wipe or dissolve instead of a flat crossfade.",
      "fader": "The A↔B crossfade position: 0 shows only IN A, 1 shows only IN B, and in between the two are blended by the amount the A/B FX dropdown's shape allows (a plain fade at the 0.5 default is a 50/50 mix). Clamped to 0..1, and the result is the mix that feeds both the SEND output and the dry side of the dry/wet stage."
    }
  },
  "lfo": {
    "explanation": "A low-frequency modulation source: one oscillator emits the same wave at four phase taps (0°/90°/180°/270°) so a single LFO can sweep several voices in stereo or quadrature without re-tuning. Rate sets the cycle speed, Shape continuously morphs the waveform (sine → saw → square), and Depth scales the swing. In a shared/multiplayer rack the phase is anchored to the rack's shared clock so every client sees the same value at the same moment; solo on the public canvas it simply free-runs from phase 0.",
    "inputs": {
      "clock": "External clock — each rising edge (crossing above 0.5) hard-resets the oscillator to phase 0, locking the LFO to an incoming pulse train (e.g. a shared sequencer's tempo). The reset is intentionally hard with no smoothing, so a click on the edge is expected; Rate still sets the speed between pulses — the clock only re-zeros the phase, it does not measure the period or change the rate.",
      "depth_cv": "CV that sums into the Depth control, modulating the output swing amount the same way the Rate/Shape CV inputs offset their params (labeled DEPTH on the panel).",
      "rate": "CV that scales the Rate knob on a logarithmic axis — ±1 multiplies the rate by about 100× / one-hundredth (≈ ±6.6 octaves of speed). Sample-and-held once at the start of each audio block so multiple clients stay phase-aligned despite sub-block CV latency differences.",
      "shape": "CV that displaces the Shape control, sliding the waveform morph (sine → saw → square) up or down. Read per-sample (a-rate) so the morph stays smooth."
    },
    "outputs": {
      "phase0": "The LFO at 0° (the reference phase). Bipolar wave centered on 0; its swing magnitude is set by Depth (0 = flat/still, 0.5 = unity ±1, 1 = ±2).",
      "phase180": "The same LFO advanced half a cycle (phase + 0.5) — the 180° tap; for the sine shape this is a polarity inversion (moves opposite phase0), useful for ping-pong / push-pull modulation.",
      "phase270": "The same LFO advanced three-quarters of a cycle (phase + 0.75) — the 270° tap, completing the 0/90/180/270 quadrature set off one shared oscillator.",
      "phase90": "The same LFO advanced a quarter cycle (phase + 0.25) — the 90° tap, useful as the offset partner for quadrature/stereo modulation."
    },
    "controls": {
      "depth": "Output amplitude / swing, applied as gain = depth × 2 and not clamped: 0 = still (flat at the 0 center, no modulation), 0.5 = unity ±1 (the default, matches legacy patches), 1 = ±2 (deliberately beyond the normal ±1 range). Orthogonal to shape — it only scales the swing, never shifts the center.",
      "rate": "How fast the LFO cycles, from 0.01 Hz (one sweep per ~100 s) to 100 Hz (audio-rate for FM-style use), on a log fader. Sets the speed shared by all four phase outputs; the clock input overrides phase, not rate.",
      "shape": "Continuously morphs the waveform across the 0–2 range: 0 = sine, 1 = saw, 2 = square, with smooth crossfades in between (e.g. value 0.5 = halfway sine↔saw). The fader's glyphs mark sine / saw / square."
    }
  },
  "sequencer": {
    "explanation": "A step sequencer that walks a playhead across up to 128 steps (8 pages of 16), emitting each lit step's note as pitch CV plus a gate, driven by its own BPM clock or an external clock fed into CLOCK IN. Mental model: every step holds a note + an on/off gate + an optional chord; the playhead advances one 16th-note step per beat-subdivision (or one step per incoming clock edge), playing lit steps and resting on dark ones, and you can save up to 8 whole patterns into quicksave slots and switch between them live (instantly, or queued to swap cleanly at the loop's end). The whole transport (play/stop, reset, slot switching, next/prev/random navigation) is also drivable hands-free by patching gates into the CV inputs.",
    "inputs": {
      "clock": "External clock: each rising edge advances the playhead exactly one step. While anything is patched here the internal BPM is ignored and the incoming pulses set the pace; unpatch to fall back to the BPM clock. Patching a clock alone also runs the sequencer (the pulses act as the play signal).",
      "next_cv": "A rising edge latches a 'move to the next filled slot' request that is applied at the end of the current loop (quantized, not instant); it skips empty slots and wraps around. A later explicit slot queue cancels it; a later nav pulse replaces it.",
      "play_cv": "A rising edge toggles play/stop (each pulse flips the current run state); when patched it takes priority over the clock-as-play behavior.",
      "prev_cv": "A rising edge latches a 'move to the previous filled slot' request, applied at the end of the current loop (skips empties, wraps around).",
      "queue1_cv": "A rising edge queues pattern slot 1: it finishes the current loop, then switches to slot 1 and restarts from step 1. An explicit slot queue overrides any pending next/prev/random navigation.",
      "queue2_cv": "A rising edge queues pattern slot 2 — applied at the end of the current loop, then plays slot 2 from step 1 (does nothing if slot 2 is empty).",
      "queue3_cv": "A rising edge queues pattern slot 3 — applied at the end of the current loop, then plays slot 3 from step 1 (does nothing if slot 3 is empty).",
      "queue4_cv": "A rising edge queues pattern slot 4 — applied at the end of the current loop, then plays slot 4 from step 1 (does nothing if slot 4 is empty).",
      "queue5_cv": "A rising edge queues pattern slot 5 — applied at the end of the current loop, then plays slot 5 from step 1 (does nothing if slot 5 is empty).",
      "queue6_cv": "A rising edge queues pattern slot 6 — applied at the end of the current loop, then plays slot 6 from step 1 (does nothing if slot 6 is empty).",
      "queue7_cv": "A rising edge queues pattern slot 7 — applied at the end of the current loop, then plays slot 7 from step 1 (does nothing if slot 7 is empty).",
      "queue8_cv": "A rising edge queues pattern slot 8 — applied at the end of the current loop, then plays slot 8 from step 1 (does nothing if slot 8 is empty).",
      "random_cv": "A rising edge latches a 'jump to a random filled slot' request, applied at the end of the current loop.",
      "reset_cv": "A rising edge snaps the playhead back to step 1 and restarts the loop. If the sequence happens to be wrapping to step 1 on its own right then, the reset is a no-op so you don't get a doubled downbeat."
    },
    "outputs": {
      "clock": "A short ~10 ms pulse fired on every step advance, regardless of whether that step is on or off — it's the 'I just stepped' signal. Patch it into another sequencer's CLOCK IN to chain them in lockstep.",
      "gate": "Goes high while a lit step is playing (high if any chord note fires this step) and low on rests; how long it stays high within the step is set by the gate-length control — patch this into an envelope or VCA to shape each note.",
      "pitch": "The current step's note as pitch CV (V/oct) across the poly chord lanes; a mono pitch input automatically receives just the root note. With sample & hold on (the default) it only updates on steps that fire and holds steady through rests, so a held note doesn't glitch."
    },
    "controls": {
      "bpm": "Internal tempo in beats per minute (each step is a 16th note, so the step rate is 4x the BPM), used only when nothing is patched into CLOCK IN; with an external clock patched, BPM no longer sets the pace and just feeds the gate-length math.",
      "gateLength": "How much of each step the gate stays high, from a short 10% stab to a near-legato 95% (it always closes just before the next step, never overlapping it); longer values keep envelopes open most of the step.",
      "isPlaying": "The run/stop state: 1 plays, 0 stops and forces the gate low. Starting playback snaps the playhead back to step 1. (If an external clock is patched, the clock edges can drive stepping even while this reads stopped.)",
      "length": "How many steps the playhead walks before wrapping back to step 1; raising it past 16 reveals more pages, lowering it shortens the loop (steps beyond the length still hold their notes but are skipped and shown dimmed).",
      "octave": "Shifts every step's pitch up or down by whole octaves at once (-2 to +2); chords transpose as a block so their internal intervals stay intact.",
      "quicksave-mode-load": "LOAD arm — click it, then click a slot to switch to that saved pattern instantly.",
      "quicksave-mode-queue": "QUEUE arm — click it, then click a slot to queue that pattern; the swap happens cleanly at the end of the current loop instead of immediately.",
      "quicksave-mode-save": "SAVE arm — click it, then click a slot 1–8 to write the current pattern (steps + BPM/length/octave/gate/swing) into that slot.",
      "quicksave-play": "Play / Stop (transport row) — same run/stop control as the header PLAY button.",
      "quicksave-reset": "Reset — snaps the playhead back to step 1 without stopping playback.",
      "quicksave-slot-{n}": "Pattern slot {n} of 8 — what a click does depends on the armed mode button: SAVE writes the current pattern (steps + BPM/length/octave/gate/swing) into this slot, LOAD switches to it instantly, and QUEUE waits until the current loop finishes and then swaps to it; a filled slot shows differently from an empty one.",
      "seq-chord-{n}": "Step {n}'s chord mode — click to cycle mono (single note) to maj (major triad) to min (minor triad); a chord broadcasts its notes across the poly pitch lanes so a polyphonic voice plays all of them, while a mono pitch sink still hears just the root.",
      "seq-gate-{n}": "Step {n} on/off — lit = it plays its note when the playhead reaches it; unlit = a rest (the gate stays low and, with sample & hold on, the pitch just holds the previous note).",
      "sequencer-hold": "HOLD — freezes the visible page so the grid stops auto-following the playhead across pages; off lets the view track the playing step.",
      "sequencer-next": "Page ▶ — view the next 16-step page (only when the pattern length spans more than 16 steps); also engages HOLD like the ◀ button.",
      "sequencer-play": "Play / Stop (header) — starts or stops the sequencer; starting snaps the playhead back to step 1. Same run/stop state as the isPlaying control and the transport-row PLAY.",
      "sequencer-prev": "Page ◀ — view the previous 16-step page of the grid; also engages HOLD so playback won't auto-scroll the view away. A marker on the arrow shows when the playhead is on a page you're not viewing.",
      "sequencer-snh-toggle": "Sample & Hold toggle (S&H / OFF) — the button form of the snh control: on (default) latches the pitch CV to the gate edge and holds it through rests, off lets pitch run continuously.",
      "snh": "Sample & hold on the pitch output, on by default: when on, the pitch CV is rewritten only on a step that actually fires a note, so it latches to the gate and holds steady through rests; turn it off for continuous pitch that can change on every step (including back toward rest).",
      "swing": "Shuffles the rhythm by lengthening the on-beat steps and shortening the off-beat steps that follow them, which pushes every off-beat later for a looser feel; 0 is dead-straight, higher values deepen the shuffle. Internal-clock only (an external clock sets its own timing)."
    }
  }
};
