// packages/web/src/lib/docs/modules-manifest.ts
//
// AUTO-GENERATED by packages/web/scripts/build-modules-manifest.mjs.
// DO NOT EDIT BY HAND. Regenerate with `flox activate -- task docs:manifest`.
//
// Source of truth: packages/web/src/lib/audio/modules/*.ts (parsed at build
// time from each module's exported AudioModuleDef literal). The /docs routes
// import this file for per-module pages + the catalog gallery.

export interface ManifestPort {
  id: string;
  type: string;
  paramTarget?: string;
  note: string;
}

export interface ManifestParam {
  id: string;
  label: string;
  defaultValue: number | null;
  min: number | null;
  max: number | null;
  curve: string;
  units?: string;
}

export interface ManifestModule {
  file: string;
  sourceUrl: string;
  type: string;
  label: string;
  category: string;
  schemaVersion: number;
  maxInstances?: number;
  description: string;
  inputs: ManifestPort[];
  outputs: ManifestPort[];
  params: ManifestParam[];
}

export interface Manifest {
  generatedAt: string;
  moduleCount: number;
  categories: string[];
  modules: ManifestModule[];
  warnings: string[];
}

export const manifest: Manifest = {
  "generatedAt": "2026-05-07T19:38:57.293Z",
  "moduleCount": 19,
  "categories": [
    "sources",
    "modulation",
    "filters",
    "effects",
    "utilities",
    "output"
  ],
  "modules": [
    {
      "file": "analog-vco.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/analog-vco.ts",
      "type": "analogVco",
      "label": "Analog VCO",
      "category": "sources",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "pitch",
          "type": "pitch",
          "note": "V/oct pitch input."
        },
        {
          "id": "fm",
          "type": "audio",
          "note": "Audio-rate FM input (depth set by FM param)."
        }
      ],
      "outputs": [
        {
          "id": "saw",
          "type": "audio",
          "note": "Sawtooth output."
        },
        {
          "id": "square",
          "type": "audio",
          "note": "Square output (PW-modulated)."
        },
        {
          "id": "triangle",
          "type": "audio",
          "note": "Triangle output."
        },
        {
          "id": "sine",
          "type": "audio",
          "note": "Sine output."
        }
      ],
      "params": [
        {
          "id": "tune",
          "label": "Tune",
          "defaultValue": 0,
          "min": -36,
          "max": 36,
          "curve": "linear",
          "units": "semi"
        },
        {
          "id": "fine",
          "label": "Fine",
          "defaultValue": 0,
          "min": -100,
          "max": 100,
          "curve": "linear",
          "units": "cent"
        },
        {
          "id": "fmAmount",
          "label": "FM",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "pw",
          "label": "PW",
          "defaultValue": 0.5,
          "min": 0.05,
          "max": 0.95,
          "curve": "linear"
        }
      ],
      "description": "Analog-style oscillator with saw / square / triangle / sine outputs and FM input."
    },
    {
      "file": "drummergirl.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/drummergirl.ts",
      "type": "drummergirl",
      "label": "DRUMMERGIRL",
      "category": "sources",
      "schemaVersion": 2,
      "inputs": [
        {
          "id": "gate",
          "type": "gate",
          "note": "Trigger."
        },
        {
          "id": "pitch",
          "type": "cv",
          "paramTarget": "pitch",
          "note": "CV → pitch."
        },
        {
          "id": "tone",
          "type": "cv",
          "paramTarget": "tone",
          "note": "CV → tone."
        },
        {
          "id": "shape",
          "type": "cv",
          "paramTarget": "shape",
          "note": "CV → shape."
        },
        {
          "id": "volume",
          "type": "cv",
          "paramTarget": "volume",
          "note": "CV → volume param."
        },
        {
          "id": "decay",
          "type": "cv",
          "paramTarget": "decay",
          "note": "CV → decay param."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Mono drum out."
        }
      ],
      "params": [
        {
          "id": "pitch",
          "label": "Pitch",
          "defaultValue": 0,
          "min": -36,
          "max": 36,
          "curve": "linear",
          "units": "semi"
        },
        {
          "id": "tone",
          "label": "Tone",
          "defaultValue": 0.3,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "shape",
          "label": "Shape",
          "defaultValue": 0.3,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "volume",
          "label": "Volume",
          "defaultValue": 1,
          "min": 0,
          "max": 2,
          "curve": "linear"
        },
        {
          "id": "decay",
          "label": "Decay",
          "defaultValue": 0.15,
          "min": 0.001,
          "max": 0.5,
          "curve": "log",
          "units": "s"
        }
      ],
      "description": "Gate-triggered drum voice (kick / snare / hat morph)."
    },
    {
      "file": "meowbox.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/meowbox.ts",
      "type": "meowbox",
      "label": "MEOWBOX",
      "category": "sources",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "gate",
          "type": "gate",
          "note": "Trigger."
        },
        {
          "id": "pitch",
          "type": "cv",
          "paramTarget": "pitch",
          "note": "CV → pitch."
        },
        {
          "id": "morph",
          "type": "cv",
          "paramTarget": "morph",
          "note": "CV → vowel morph."
        },
        {
          "id": "decay",
          "type": "cv",
          "paramTarget": "decay",
          "note": "CV → decay."
        },
        {
          "id": "level",
          "type": "cv",
          "paramTarget": "level",
          "note": "CV → output level."
        }
      ],
      "outputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Stereo L out."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Stereo R out."
        }
      ],
      "params": [
        {
          "id": "pitch",
          "label": "Ptch",
          "defaultValue": 0,
          "min": -36,
          "max": 36,
          "curve": "linear",
          "units": "semi"
        },
        {
          "id": "morph",
          "label": "Morph",
          "defaultValue": 0.25,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "decay",
          "label": "Dcy",
          "defaultValue": 0.4,
          "min": 0.05,
          "max": 2,
          "curve": "log",
          "units": "s"
        },
        {
          "id": "level",
          "label": "Lvl",
          "defaultValue": 1,
          "min": 0,
          "max": 2,
          "curve": "linear"
        }
      ],
      "description": "Gate-triggered cat-vocal synth voice (formant bank + harmonic + noise excitation)."
    },
    {
      "file": "wavetable-vco.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/wavetable-vco.ts",
      "type": "wavetableVco",
      "label": "Wavetable VCO",
      "category": "sources",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "pitch",
          "type": "pitch",
          "note": "V/oct pitch input."
        },
        {
          "id": "fm",
          "type": "audio",
          "note": "Audio-rate FM input."
        },
        {
          "id": "wavePos",
          "type": "cv",
          "note": "CV → wavetable scan position."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Mixed wavetable output."
        }
      ],
      "params": [
        {
          "id": "tune",
          "label": "Tune",
          "defaultValue": 0,
          "min": -36,
          "max": 36,
          "curve": "linear",
          "units": "st"
        },
        {
          "id": "fine",
          "label": "Fine",
          "defaultValue": 0,
          "min": -100,
          "max": 100,
          "curve": "linear",
          "units": "¢"
        },
        {
          "id": "wavePos",
          "label": "Wave",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "fmAmount",
          "label": "FM",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Wavetable oscillator that morphs saw → square → triangle → sine across a 16-frame table."
    },
    {
      "file": "adsr.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/adsr.ts",
      "type": "adsr",
      "label": "ADSR",
      "category": "modulation",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "gate",
          "type": "gate",
          "note": "Triggers attack → decay → sustain on rising edge; release on falling."
        },
        {
          "id": "attack",
          "type": "cv",
          "paramTarget": "attack",
          "note": "CV → attack param."
        },
        {
          "id": "decay",
          "type": "cv",
          "paramTarget": "decay",
          "note": "CV → decay param."
        },
        {
          "id": "sustain",
          "type": "cv",
          "paramTarget": "sustain",
          "note": "CV → sustain param."
        },
        {
          "id": "release",
          "type": "cv",
          "paramTarget": "release",
          "note": "CV → release param."
        }
      ],
      "outputs": [
        {
          "id": "env",
          "type": "cv",
          "note": "Envelope CV out (0..1)."
        }
      ],
      "params": [
        {
          "id": "attack",
          "label": "A",
          "defaultValue": 0.005,
          "min": 0.001,
          "max": 10,
          "curve": "log",
          "units": "s"
        },
        {
          "id": "decay",
          "label": "D",
          "defaultValue": 0.1,
          "min": 0.001,
          "max": 10,
          "curve": "log",
          "units": "s"
        },
        {
          "id": "sustain",
          "label": "S",
          "defaultValue": 0.7,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "release",
          "label": "R",
          "defaultValue": 0.3,
          "min": 0.001,
          "max": 10,
          "curve": "log",
          "units": "s"
        }
      ],
      "description": "Gate-triggered attack-decay-sustain-release envelope. Outputs CV."
    },
    {
      "file": "cartesian.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/cartesian.ts",
      "type": "cartesian",
      "label": "Cartesian",
      "category": "modulation",
      "schemaVersion": 4,
      "inputs": [
        {
          "id": "clock",
          "type": "gate",
          "note": "Step advance (rising edge)."
        },
        {
          "id": "x_cv",
          "type": "cv",
          "note": "CV scrub on the X axis."
        },
        {
          "id": "y_cv",
          "type": "cv",
          "note": "CV scrub on the Y axis."
        },
        {
          "id": "lfo_clock",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        }
      ],
      "outputs": [
        {
          "id": "pitch",
          "type": "polyPitchGate",
          "note": "V/oct pitch out."
        },
        {
          "id": "gate",
          "type": "gate",
          "note": "Gate out."
        },
        {
          "id": "clock",
          "type": "gate",
          "note": "Step advance (rising edge)."
        },
        {
          "id": "lfo_x",
          "type": "cv",
          "note": "Control voltage."
        },
        {
          "id": "lfo_y",
          "type": "cv",
          "note": "Control voltage."
        }
      ],
      "params": [
        {
          "id": "mode",
          "label": "Mode",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "octave",
          "label": "Oct",
          "defaultValue": 0,
          "min": -2,
          "max": 2,
          "curve": "discrete"
        },
        {
          "id": "gateLength",
          "label": "Gate",
          "defaultValue": 0.5,
          "min": 0.1,
          "max": 0.95,
          "curve": "linear"
        },
        {
          "id": "lfoDiv",
          "label": "Div",
          "defaultValue": 3,
          "min": 0,
          "max": 7,
          "curve": "discrete"
        },
        {
          "id": "lfoShape",
          "label": "Wave",
          "defaultValue": 0,
          "min": 0,
          "max": 3,
          "curve": "linear"
        }
      ],
      "description": "4×4 grid sequencer. Steps via clock; X/Y CV inputs scrub freely across the grid."
    },
    {
      "file": "lfo.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/lfo.ts",
      "type": "lfo",
      "label": "LFO",
      "category": "modulation",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "clock",
          "type": "gate",
          "note": "External clock — locks LFO rate to incoming pulses."
        },
        {
          "id": "rate",
          "type": "cv",
          "paramTarget": "rate",
          "note": "CV → rate AudioParam."
        },
        {
          "id": "shape",
          "type": "cv",
          "paramTarget": "shape",
          "note": "CV → wave shape."
        }
      ],
      "outputs": [
        {
          "id": "phase0",
          "type": "cv",
          "note": "LFO at 0°."
        },
        {
          "id": "phase90",
          "type": "cv",
          "note": "LFO at 90°."
        },
        {
          "id": "phase180",
          "type": "cv",
          "note": "LFO at 180°."
        },
        {
          "id": "phase270",
          "type": "cv",
          "note": "LFO at 270°."
        }
      ],
      "params": [
        {
          "id": "rate",
          "label": "Rate",
          "defaultValue": 1,
          "min": 0.01,
          "max": 100,
          "curve": "log",
          "units": "Hz"
        },
        {
          "id": "shape",
          "label": "Shape",
          "defaultValue": 0,
          "min": 0,
          "max": 2,
          "curve": "linear"
        }
      ],
      "description": "Clockable LFO with four phase outputs (0° / 90° / 180° / 270°)."
    },
    {
      "file": "sequencer.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/sequencer.ts",
      "type": "sequencer",
      "label": "Sequencer",
      "category": "modulation",
      "schemaVersion": 4,
      "inputs": [
        {
          "id": "clock",
          "type": "gate",
          "note": "External clock (rising edges advance the step pointer)."
        }
      ],
      "outputs": [
        {
          "id": "pitch",
          "type": "polyPitchGate",
          "note": "V/oct pitch out."
        },
        {
          "id": "gate",
          "type": "gate",
          "note": "Gate out (high while step is on)."
        },
        {
          "id": "clock",
          "type": "gate",
          "note": "External clock (rising edges advance the step pointer)."
        }
      ],
      "params": [
        {
          "id": "bpm",
          "label": "BPM",
          "defaultValue": 120,
          "min": 30,
          "max": 300,
          "curve": "linear"
        },
        {
          "id": "length",
          "label": "Len",
          "defaultValue": 16,
          "min": 1,
          "max": 32,
          "curve": "discrete"
        },
        {
          "id": "octave",
          "label": "Oct",
          "defaultValue": 0,
          "min": -2,
          "max": 2,
          "curve": "discrete"
        },
        {
          "id": "gateLength",
          "label": "Gate",
          "defaultValue": 0.5,
          "min": 0.1,
          "max": 0.95,
          "curve": "linear"
        },
        {
          "id": "swing",
          "label": "Sw",
          "defaultValue": 0,
          "min": 0,
          "max": 0.75,
          "curve": "linear"
        },
        {
          "id": "isPlaying",
          "label": "Play",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        }
      ],
      "description": "32-step sequencer with internal BPM clock or external clock input."
    },
    {
      "file": "timelorde.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/timelorde.ts",
      "type": "timelorde",
      "label": "TIMELORDE",
      "category": "modulation",
      "schemaVersion": 1,
      "maxInstances": 1,
      "inputs": [
        {
          "id": "clock",
          "type": "gate",
          "note": "External clock — snaps 1x to incoming rising edges; falls back to internal BPM after ~2 master periods."
        }
      ],
      "outputs": [
        {
          "id": "1x",
          "type": "gate",
          "note": "Master tempo gate."
        },
        {
          "id": "4x",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "2x",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/2",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/3",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/4",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/8",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/12",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/16",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/32",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "1/64",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        },
        {
          "id": "swing",
          "type": "gate",
          "note": "Gate signal (rising/falling edge)."
        }
      ],
      "params": [
        {
          "id": "bpm",
          "label": "BPM",
          "defaultValue": 120,
          "min": 10,
          "max": 300,
          "curve": "log",
          "units": "bpm"
        },
        {
          "id": "swingAmount",
          "label": "Swing",
          "defaultValue": 0,
          "min": 0,
          "max": 90,
          "curve": "linear",
          "units": "deg"
        },
        {
          "id": "swingSource",
          "label": "Src",
          "defaultValue": 0,
          "min": 0,
          "max": 10,
          "curve": "discrete"
        },
        {
          "id": "isPlaying",
          "label": "Play",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        }
      ],
      "description": "Singleton master clock. Internal or external BPM, twelve clock-divider outputs."
    },
    {
      "file": "filter.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/filter.ts",
      "type": "filter",
      "label": "Filter",
      "category": "filters",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio in."
        },
        {
          "id": "cutoff",
          "type": "cv",
          "note": "CV → cutoff freq."
        },
        {
          "id": "res",
          "type": "cv",
          "note": "CV → resonance."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio in."
        }
      ],
      "params": [
        {
          "id": "cutoff",
          "label": "Cutoff",
          "defaultValue": 1000,
          "min": 20,
          "max": 20000,
          "curve": "log",
          "units": "Hz"
        },
        {
          "id": "resonance",
          "label": "Res",
          "defaultValue": 0.1,
          "min": 0,
          "max": 0.99,
          "curve": "linear"
        },
        {
          "id": "mode",
          "label": "Mode",
          "defaultValue": 0,
          "min": 0,
          "max": 2,
          "curve": "discrete"
        }
      ],
      "description": "Multi-mode resonant filter (low / band / high). CV inputs sum into cutoff and resonance."
    },
    {
      "file": "qbrt.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/qbrt.ts",
      "type": "qbrt",
      "label": "QBRT",
      "category": "filters",
      "schemaVersion": 2,
      "inputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Stereo input L."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Stereo input R."
        },
        {
          "id": "ping",
          "type": "gate",
          "note": "Gate → click excitation."
        },
        {
          "id": "cutoff",
          "type": "cv",
          "paramTarget": "cutoff",
          "note": "CV → cutoff."
        },
        {
          "id": "resonance",
          "type": "cv",
          "paramTarget": "resonance",
          "note": "CV → resonance."
        },
        {
          "id": "mode",
          "type": "cv",
          "paramTarget": "mode",
          "note": "CV → filter mode."
        },
        {
          "id": "pingDecay",
          "type": "cv",
          "paramTarget": "pingDecay",
          "note": "CV → ping envelope decay."
        }
      ],
      "outputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Stereo input L."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Stereo input R."
        }
      ],
      "params": [
        {
          "id": "cutoff",
          "label": "Cut",
          "defaultValue": 1000,
          "min": 20,
          "max": 20000,
          "curve": "log",
          "units": "Hz"
        },
        {
          "id": "resonance",
          "label": "Res",
          "defaultValue": 0.7,
          "min": 0,
          "max": 0.99,
          "curve": "linear"
        },
        {
          "id": "mode",
          "label": "Mode",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "pingDecay",
          "label": "Ping",
          "defaultValue": 0.15,
          "min": 0.005,
          "max": 0.5,
          "curve": "log",
          "units": "s"
        }
      ],
      "description": "Stereo state-variable filter with vactrol-style ping input."
    },
    {
      "file": "charlottes-echos.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/charlottes-echos.ts",
      "type": "charlottesEchos",
      "label": "CHARLOTTE'S ECHOS",
      "category": "effects",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Stereo L in / out."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Stereo R in / out."
        },
        {
          "id": "delay",
          "type": "cv",
          "paramTarget": "delay",
          "note": "CV → delay time."
        }
      ],
      "outputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Stereo L in / out."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Stereo R in / out."
        }
      ],
      "params": [
        {
          "id": "delay",
          "label": "Delay",
          "defaultValue": 0.4,
          "min": 0.001,
          "max": 1.5,
          "curve": "log",
          "units": "s"
        },
        {
          "id": "feedback",
          "label": "Fbk",
          "defaultValue": 0.5,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "decay",
          "label": "Decay",
          "defaultValue": 0.2,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "pitchUp",
          "label": "Ptch",
          "defaultValue": 0,
          "min": 0,
          "max": 0.2,
          "curve": "linear"
        },
        {
          "id": "mix",
          "label": "Mix",
          "defaultValue": 0.5,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Destructive multi-head stereo delay. Pitch-shifted feedback with decay."
    },
    {
      "file": "destroy.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/destroy.ts",
      "type": "destroy",
      "label": "DESTROY",
      "category": "effects",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio in / out."
        },
        {
          "id": "decimate",
          "type": "cv",
          "paramTarget": "decimate",
          "note": "CV → decimation factor."
        },
        {
          "id": "bits",
          "type": "cv",
          "paramTarget": "bits",
          "note": "CV → bit depth."
        },
        {
          "id": "wet",
          "type": "cv",
          "paramTarget": "wet",
          "note": "CV → wet/dry mix."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio in / out."
        }
      ],
      "params": [
        {
          "id": "decimate",
          "label": "Dec",
          "defaultValue": 1,
          "min": 1,
          "max": 64,
          "curve": "linear"
        },
        {
          "id": "bits",
          "label": "Bits",
          "defaultValue": 16,
          "min": 1,
          "max": 16,
          "curve": "linear"
        },
        {
          "id": "wet",
          "label": "Wet",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Bitcrusher + decimator distortion."
    },
    {
      "file": "reverb.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/reverb.ts",
      "type": "reverb",
      "label": "Reverb",
      "category": "effects",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Pre-reverb mono in / wet+dry mix out."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Pre-reverb mono in / wet+dry mix out."
        }
      ],
      "params": [
        {
          "id": "size",
          "label": "Size",
          "defaultValue": 0.5,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "damp",
          "label": "Damp",
          "defaultValue": 0.3,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "mix",
          "label": "Mix",
          "defaultValue": 0.3,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Algorithmic reverb. Size / damp / mix."
    },
    {
      "file": "mixer.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/mixer.ts",
      "type": "mixer",
      "label": "Mixer",
      "category": "utilities",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "in1",
          "type": "audio",
          "note": "Channel 1 input."
        },
        {
          "id": "in2",
          "type": "audio",
          "note": "Channel 2 input."
        },
        {
          "id": "in3",
          "type": "audio",
          "note": "Channel 3 input."
        },
        {
          "id": "in4",
          "type": "audio",
          "note": "Channel 4 input."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio signal."
        }
      ],
      "params": [
        {
          "id": "ch1",
          "label": "Ch1",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch2",
          "label": "Ch2",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch3",
          "label": "Ch3",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch4",
          "label": "Ch4",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "master",
          "label": "Master",
          "defaultValue": 1,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Four-channel mono summing mixer with master gain."
    },
    {
      "file": "mixmstrs.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/mixmstrs.ts",
      "type": "mixmstrs",
      "label": "MIXMSTRS",
      "category": "utilities",
      "schemaVersion": 1,
      "maxInstances": 1,
      "inputs": [
        {
          "id": "ch1L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch1R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch2L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch2R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch3L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch3R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch4L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch4R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ret1L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ret1R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ret2L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ret2R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "ch1_volume",
          "type": "cv",
          "paramTarget": "ch1_volume",
          "note": "CV → ch1_volume param."
        },
        {
          "id": "ch1_low",
          "type": "cv",
          "paramTarget": "ch1_low",
          "note": "CV → ch1_low param."
        },
        {
          "id": "ch1_mid",
          "type": "cv",
          "paramTarget": "ch1_mid",
          "note": "CV → ch1_mid param."
        },
        {
          "id": "ch1_high",
          "type": "cv",
          "paramTarget": "ch1_high",
          "note": "CV → ch1_high param."
        },
        {
          "id": "ch1_thresh",
          "type": "cv",
          "paramTarget": "ch1_thresh",
          "note": "CV → ch1_thresh param."
        },
        {
          "id": "ch1_ratio",
          "type": "cv",
          "paramTarget": "ch1_ratio",
          "note": "CV → ch1_ratio param."
        },
        {
          "id": "ch1_compEnable",
          "type": "cv",
          "paramTarget": "ch1_compEnable",
          "note": "CV → ch1_compEnable param."
        },
        {
          "id": "ch1_send1",
          "type": "cv",
          "paramTarget": "ch1_send1",
          "note": "CV → ch1_send1 param."
        },
        {
          "id": "ch1_send2",
          "type": "cv",
          "paramTarget": "ch1_send2",
          "note": "CV → ch1_send2 param."
        },
        {
          "id": "ch2_volume",
          "type": "cv",
          "paramTarget": "ch2_volume",
          "note": "CV → ch2_volume param."
        },
        {
          "id": "ch2_low",
          "type": "cv",
          "paramTarget": "ch2_low",
          "note": "CV → ch2_low param."
        },
        {
          "id": "ch2_mid",
          "type": "cv",
          "paramTarget": "ch2_mid",
          "note": "CV → ch2_mid param."
        },
        {
          "id": "ch2_high",
          "type": "cv",
          "paramTarget": "ch2_high",
          "note": "CV → ch2_high param."
        },
        {
          "id": "ch2_thresh",
          "type": "cv",
          "paramTarget": "ch2_thresh",
          "note": "CV → ch2_thresh param."
        },
        {
          "id": "ch2_ratio",
          "type": "cv",
          "paramTarget": "ch2_ratio",
          "note": "CV → ch2_ratio param."
        },
        {
          "id": "ch2_compEnable",
          "type": "cv",
          "paramTarget": "ch2_compEnable",
          "note": "CV → ch2_compEnable param."
        },
        {
          "id": "ch2_send1",
          "type": "cv",
          "paramTarget": "ch2_send1",
          "note": "CV → ch2_send1 param."
        },
        {
          "id": "ch2_send2",
          "type": "cv",
          "paramTarget": "ch2_send2",
          "note": "CV → ch2_send2 param."
        },
        {
          "id": "ch3_volume",
          "type": "cv",
          "paramTarget": "ch3_volume",
          "note": "CV → ch3_volume param."
        },
        {
          "id": "ch3_low",
          "type": "cv",
          "paramTarget": "ch3_low",
          "note": "CV → ch3_low param."
        },
        {
          "id": "ch3_mid",
          "type": "cv",
          "paramTarget": "ch3_mid",
          "note": "CV → ch3_mid param."
        },
        {
          "id": "ch3_high",
          "type": "cv",
          "paramTarget": "ch3_high",
          "note": "CV → ch3_high param."
        },
        {
          "id": "ch3_thresh",
          "type": "cv",
          "paramTarget": "ch3_thresh",
          "note": "CV → ch3_thresh param."
        },
        {
          "id": "ch3_ratio",
          "type": "cv",
          "paramTarget": "ch3_ratio",
          "note": "CV → ch3_ratio param."
        },
        {
          "id": "ch3_compEnable",
          "type": "cv",
          "paramTarget": "ch3_compEnable",
          "note": "CV → ch3_compEnable param."
        },
        {
          "id": "ch3_send1",
          "type": "cv",
          "paramTarget": "ch3_send1",
          "note": "CV → ch3_send1 param."
        },
        {
          "id": "ch3_send2",
          "type": "cv",
          "paramTarget": "ch3_send2",
          "note": "CV → ch3_send2 param."
        },
        {
          "id": "ch4_volume",
          "type": "cv",
          "paramTarget": "ch4_volume",
          "note": "CV → ch4_volume param."
        },
        {
          "id": "ch4_low",
          "type": "cv",
          "paramTarget": "ch4_low",
          "note": "CV → ch4_low param."
        },
        {
          "id": "ch4_mid",
          "type": "cv",
          "paramTarget": "ch4_mid",
          "note": "CV → ch4_mid param."
        },
        {
          "id": "ch4_high",
          "type": "cv",
          "paramTarget": "ch4_high",
          "note": "CV → ch4_high param."
        },
        {
          "id": "ch4_thresh",
          "type": "cv",
          "paramTarget": "ch4_thresh",
          "note": "CV → ch4_thresh param."
        },
        {
          "id": "ch4_ratio",
          "type": "cv",
          "paramTarget": "ch4_ratio",
          "note": "CV → ch4_ratio param."
        },
        {
          "id": "ch4_compEnable",
          "type": "cv",
          "paramTarget": "ch4_compEnable",
          "note": "CV → ch4_compEnable param."
        },
        {
          "id": "ch4_send1",
          "type": "cv",
          "paramTarget": "ch4_send1",
          "note": "CV → ch4_send1 param."
        },
        {
          "id": "ch4_send2",
          "type": "cv",
          "paramTarget": "ch4_send2",
          "note": "CV → ch4_send2 param."
        },
        {
          "id": "master_volume",
          "type": "cv",
          "paramTarget": "master_volume",
          "note": "CV → master_volume param."
        }
      ],
      "outputs": [
        {
          "id": "masterL",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "masterR",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "send1L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "send1R",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "send2L",
          "type": "audio",
          "note": "Audio signal."
        },
        {
          "id": "send2R",
          "type": "audio",
          "note": "Audio signal."
        }
      ],
      "params": [
        {
          "id": "ch1_volume",
          "label": "1V",
          "defaultValue": 0.8,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch1_low",
          "label": "1Lo",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch1_mid",
          "label": "1Md",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch1_high",
          "label": "1Hi",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch1_thresh",
          "label": "1Th",
          "defaultValue": -12,
          "min": -36,
          "max": 0,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch1_ratio",
          "label": "1Rt",
          "defaultValue": 2,
          "min": 1,
          "max": 10,
          "curve": "linear"
        },
        {
          "id": "ch1_compEnable",
          "label": "1Cp",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "ch1_send1",
          "label": "1S1",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch1_send2",
          "label": "1S2",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch2_volume",
          "label": "2V",
          "defaultValue": 0.8,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch2_low",
          "label": "2Lo",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch2_mid",
          "label": "2Md",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch2_high",
          "label": "2Hi",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch2_thresh",
          "label": "2Th",
          "defaultValue": -12,
          "min": -36,
          "max": 0,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch2_ratio",
          "label": "2Rt",
          "defaultValue": 2,
          "min": 1,
          "max": 10,
          "curve": "linear"
        },
        {
          "id": "ch2_compEnable",
          "label": "2Cp",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "ch2_send1",
          "label": "2S1",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch2_send2",
          "label": "2S2",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch3_volume",
          "label": "3V",
          "defaultValue": 0.8,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch3_low",
          "label": "3Lo",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch3_mid",
          "label": "3Md",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch3_high",
          "label": "3Hi",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch3_thresh",
          "label": "3Th",
          "defaultValue": -12,
          "min": -36,
          "max": 0,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch3_ratio",
          "label": "3Rt",
          "defaultValue": 2,
          "min": 1,
          "max": 10,
          "curve": "linear"
        },
        {
          "id": "ch3_compEnable",
          "label": "3Cp",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "ch3_send1",
          "label": "3S1",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch3_send2",
          "label": "3S2",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch4_volume",
          "label": "4V",
          "defaultValue": 0.8,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch4_low",
          "label": "4Lo",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch4_mid",
          "label": "4Md",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch4_high",
          "label": "4Hi",
          "defaultValue": 0,
          "min": -12,
          "max": 12,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch4_thresh",
          "label": "4Th",
          "defaultValue": -12,
          "min": -36,
          "max": 0,
          "curve": "linear",
          "units": "dB"
        },
        {
          "id": "ch4_ratio",
          "label": "4Rt",
          "defaultValue": 2,
          "min": 1,
          "max": 10,
          "curve": "linear"
        },
        {
          "id": "ch4_compEnable",
          "label": "4Cp",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "ch4_send1",
          "label": "4S1",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch4_send2",
          "label": "4S2",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "master_volume",
          "label": "Master",
          "defaultValue": 0.8,
          "min": 0,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Singleton 4×stereo mixer with EQ, compressor, two stereo aux sends/returns."
    },
    {
      "file": "scope.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/scope.ts",
      "type": "scope",
      "label": "Scope",
      "category": "utilities",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "ch1",
          "type": "audio",
          "note": "Channel 1 in."
        },
        {
          "id": "ch2",
          "type": "audio",
          "note": "Channel 2 in."
        }
      ],
      "outputs": [
        {
          "id": "ch1_out",
          "type": "audio",
          "note": "Channel 1 passthrough."
        },
        {
          "id": "ch2_out",
          "type": "audio",
          "note": "Channel 2 passthrough."
        }
      ],
      "params": [
        {
          "id": "timeMs",
          "label": "Time",
          "defaultValue": 20,
          "min": 1,
          "max": 200,
          "curve": "log",
          "units": "ms"
        },
        {
          "id": "ch1Scale",
          "label": "Ch1 Sc",
          "defaultValue": 1,
          "min": 0.1,
          "max": 10,
          "curve": "log"
        },
        {
          "id": "ch1Offset",
          "label": "Ch1 Y",
          "defaultValue": 0,
          "min": -1,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch1Range",
          "label": "Ch1 R",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "ch2Scale",
          "label": "Ch2 Sc",
          "defaultValue": 1,
          "min": 0.1,
          "max": 10,
          "curve": "log"
        },
        {
          "id": "ch2Offset",
          "label": "Ch2 Y",
          "defaultValue": 0,
          "min": -1,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "ch2Range",
          "label": "Ch2 R",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        },
        {
          "id": "mode",
          "label": "XY",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "discrete"
        }
      ],
      "description": "2-channel passthrough oscilloscope. Inputs flow unchanged to outputs while an AnalyserNode samples for display."
    },
    {
      "file": "vca.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/vca.ts",
      "type": "vca",
      "label": "VCA",
      "category": "utilities",
      "schemaVersion": 1,
      "inputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio input (gets multiplied)."
        },
        {
          "id": "cv",
          "type": "cv",
          "note": "Modulation CV (gain control)."
        }
      ],
      "outputs": [
        {
          "id": "audio",
          "type": "audio",
          "note": "Audio input (gets multiplied)."
        }
      ],
      "params": [
        {
          "id": "base",
          "label": "Base",
          "defaultValue": 0,
          "min": 0,
          "max": 1,
          "curve": "linear"
        },
        {
          "id": "cvAmount",
          "label": "CV",
          "defaultValue": 1,
          "min": -1,
          "max": 1,
          "curve": "linear"
        }
      ],
      "description": "Voltage-controlled amplifier. Multiplies the audio input by base + (cv * cvAmount)."
    },
    {
      "file": "audio-out.ts",
      "sourceUrl": "https://github.com/2600hz-oscillator/patchtogether.live/blob/main/packages/web/src/lib/audio/modules/audio-out.ts",
      "type": "audioOut",
      "label": "Audio Out",
      "category": "output",
      "schemaVersion": 2,
      "inputs": [
        {
          "id": "L",
          "type": "audio",
          "note": "Mono L → host destination L."
        },
        {
          "id": "R",
          "type": "audio",
          "note": "Mono R → host destination R."
        }
      ],
      "outputs": [],
      "params": [
        {
          "id": "master",
          "label": "Master",
          "defaultValue": 0.7,
          "min": 0,
          "max": 1,
          "curve": "linear",
          "units": "gain"
        }
      ],
      "description": "Terminal stereo output. Two mono inputs (L, R) routed to the host AudioContext destination."
    }
  ],
  "warnings": []
};
