// packages/web/src/lib/docs/testing-manifest.ts
//
// AUTOGENERATED by packages/web/scripts/build-module-manifest.mjs.
// DO NOT EDIT BY HAND. Regenerate with `flox activate -- task docs:manifest`.

import type { TestingManifest } from './types';

export const testingManifest: TestingManifest = {
  "artScenarios": [
    {
      "group": "analog-vco",
      "file": "saw-c4.test.ts",
      "path": "art/scenarios/analog-vco/saw-c4.test.ts"
    },
    {
      "group": "cartesian-lfo",
      "file": "cartesian-lfo.test.ts",
      "path": "art/scenarios/cartesian-lfo/cartesian-lfo.test.ts"
    },
    {
      "group": "charlottes-echos",
      "file": "single-tap.test.ts",
      "path": "art/scenarios/charlottes-echos/single-tap.test.ts"
    },
    {
      "group": "meowbox",
      "file": "meow-c4.test.ts",
      "path": "art/scenarios/meowbox/meow-c4.test.ts"
    },
    {
      "group": "mixmstrs",
      "file": "passthrough.test.ts",
      "path": "art/scenarios/mixmstrs/passthrough.test.ts"
    },
    {
      "group": "note-pitch",
      "file": "note-pitch.test.ts",
      "path": "art/scenarios/note-pitch/note-pitch.test.ts"
    },
    {
      "group": "poly-chord",
      "file": "maj-triad.test.ts",
      "path": "art/scenarios/poly-chord/maj-triad.test.ts"
    },
    {
      "group": "timelorde",
      "file": "bpm-120-internal.test.ts",
      "path": "art/scenarios/timelorde/bpm-120-internal.test.ts"
    }
  ],
  "artBaselines": [
    {
      "group": "analog-vco",
      "file": "saw-c4.f32",
      "path": "art/baselines/analog-vco/saw-c4.f32"
    },
    {
      "group": "analog-vco",
      "file": "saw-c4.sha",
      "path": "art/baselines/analog-vco/saw-c4.sha"
    }
  ],
  "vrtImplemented": false,
  "e2eSpecs": [
    "ai-debug.spec.ts",
    "ai-smoke.spec.ts",
    "audio-gate.spec.ts",
    "auth-handshake.spec.ts",
    "auth-routes.spec.ts",
    "awareness.spec.ts",
    "capacity.spec.ts",
    "clear-load-multiwindow.spec.ts",
    "clear.spec.ts",
    "collab.spec.ts",
    "combinations.spec.ts",
    "docs.spec.ts",
    "four-modules.spec.ts",
    "keyboard-nav.spec.ts",
    "lfo-modulation-visible.spec.ts",
    "load-patch.spec.ts",
    "modulation.spec.ts",
    "modules.spec.ts",
    "node-context-menu.spec.ts",
    "note-entry.spec.ts",
    "palette.spec.ts",
    "poly-chord.spec.ts",
    "save-load.spec.ts",
    "sequencer-clock.spec.ts",
    "soak.spec.ts",
    "voice-chain-art.spec.ts",
    "voice-chain.spec.ts"
  ]
} as const;
