<script lang="ts">
  let { data } = $props();
</script>

<svelte:head>
  <title>testing · patchtogether.live</title>
  <meta name="description" content="Unit / ART / E2E test layers + port-surface consistency gates." />
</svelte:head>

<section class="hero">
  <h1>testing</h1>
  <div class="sub">Multi-layer regression coverage. Each layer scoped at a different boundary.</div>
</section>

<p>
  Three layers in CI today, by ascending integration scope: <strong>unit</strong> →
  <strong>ART</strong> → <strong>E2E</strong>. The PR gate
  (<code>flox activate -- task ci</code>) runs typecheck + unit + ART + E2E. VRT (Visual
  Regression Tests) is planned for the video domain but not yet implemented — see below.
</p>

<h2>Unit</h2>
<p>
  Vitest, fast, scoped per workspace. Lives next to the code (<code>foo.ts</code> ↔
  <code>foo.test.ts</code>). Run all unit tests:
</p>
<pre><code>flox activate -- task test</code></pre>
<p>
  Coverage areas today: graph store mutations, capacity logic, auth handshake, layout merging,
  note-entry coercion, docs module-manifest generator.
</p>

<h2>Port-surface consistency gates</h2>
<p>
  Three gates keep each module&rsquo;s I/O surface consistent across def, published manifest,
  and rendered UI — drift between them was the root cause of the <code>RIOTGIRLS</code>
  regression where the def grew dozens of CV inputs but the card only rendered three handles
  per voice (cables had nothing visible to land on).
</p>
<ol>
  <li>
    The <strong>module def</strong> at
    <code>packages/web/src/lib/&lbrace;audio,video&rbrace;/modules/&lt;type&gt;.ts</code> (the runtime source
    of truth — what the engine wires up).
  </li>
  <li>
    The <strong>published manifest</strong> at <code>/docs/modules/&lt;type&gt;</code>
    (built from <code>packages/web/src/lib/docs/module-manifest.ts</code>).
  </li>
  <li>
    The <strong>card UI</strong> at <code>packages/web/src/lib/ui/modules/&lt;Type&gt;Card.svelte</code>
    (the Svelte Flow Handle elements the user can plug cables into).
  </li>
</ol>
<ul>
  <li>
    <strong>Unit — manifest stays in sync with defs:</strong>
    <code>packages/web/src/lib/docs/module-manifest.test.ts</code> iterates over
    <code>getAllModuleSpecs()</code> and asserts the manifest&rsquo;s input/output ids equal
    the def&rsquo;s. Catches drift between the def and the docs builder.
  </li>
  <li>
    <strong>E2E — UI matches def:</strong>
    <code>e2e/tests/io-spec-consistency.spec.ts</code> spawns each module type, reads
    <code>window.__moduleSpecs</code>, and asserts every Handle&rsquo;s
    <code>data-handleid</code> matches the def.
  </li>
  <li>
    <strong>E2E — CV range uniformity:</strong>
    <code>e2e/tests/cv-range-uniformity.spec.ts</code> walks every <code>cv</code> input port
    and asserts a <code>cvScale</code> hint is declared, then drives an LFO at ±1 to confirm
    the target slider sweeps edge-to-edge. Catches the regression where a new module is added
    with a raw <code>passthrough</code> CV input, leaving an LFO touching only ~10% of the
    natural range. See <code>.myrobots/plans/cv-range-standard.md</code>.
  </li>
</ul>
<p>
  <strong>Adding a new module:</strong> the unit test iterates the registry automatically — no
  edit needed. For the E2E test, add the new <code>ModuleType</code> string to the
  <code>MODULE_TYPES</code> array in <code>io-spec-consistency.spec.ts</code> and make sure the
  card&rsquo;s <code>&lt;Handle&gt;</code> <code>id=</code> values match the def&rsquo;s port ids
  exactly. If the UI is intentionally lagging the def (e.g. some CV ports kept off-card to avoid
  chrome overload), add an entry to <code>SKIP_DEF_VS_UI</code> with a TODO pointing at the
  follow-up branch.
</p>
<p>
  Helper: <code>packages/web/src/lib/dev/module-specs.ts</code> exposes
  <code>getAllModuleSpecs()</code> as a thin projection of the registry. In dev /
  <code>VITE_E2E_HOOKS=1</code> builds it&rsquo;s also published as
  <code>window.__moduleSpecs</code>.
</p>

<h2>ART — Audio Regression Tests</h2>
<p>
  Offline render of compiled DSP through <code>node-web-audio-api</code> → Float32 PCM. Tests
  assert on FFT peak frequency, harmonic ratios, silence floor, and where deterministic,
  byte-identical match against a <code>.f32</code> baseline pinned in Git LFS. The harness lives
  at <code>art/setup/render.ts</code>.
</p>
<pre><code>flox activate -- task art           # run
flox activate -- task art:update    # regenerate .f32 + .sha baselines</code></pre>

<p>
  Browse a rendered <strong>gallery</strong> of every <code>.f32</code> baseline &mdash; a
  waveform + log-frequency spectrogram per baseline, grouped by scenario &mdash; published to
  GitHub Pages:
  <a href="https://2600hz-oscillator.github.io/patchtogether.live/art/" target="_blank" rel="noreferrer"
    >ART gallery &rarr;</a
  >. It&rsquo;s generated by <code>art/build_gallery.py</code> and republished on every push to
  main (<code>.github/workflows/art-gallery.yml</code>), the audio sibling of the
  <a href="https://2600hz-oscillator.github.io/patchtogether.live/vrt/" target="_blank" rel="noreferrer"
    >VRT gallery</a
  >.
</p>

<h3>Scenarios ({data.artScenarios.length})</h3>
<table>
  <thead><tr><th>group</th><th>spec</th></tr></thead>
  <tbody>
    {#each data.artScenarios as s (s.path)}
      <tr>
        <td>{s.group}</td>
        <td><code>{s.file}</code></td>
      </tr>
    {/each}
  </tbody>
</table>

{#if data.artBaselines.length > 0}
  <h3>Baselines ({data.artBaselines.length})</h3>
  <p>
    Pinned in Git LFS at <code>art/baselines/</code>. <code>.f32</code> = raw 32-bit PCM,
    <code>.sha</code> = sidecar hash.
  </p>
  <table>
    <thead><tr><th>group</th><th>file</th></tr></thead>
    <tbody>
      {#each data.artBaselines as b (b.path)}
        <tr>
          <td>{b.group}</td>
          <td><code>{b.file}</code></td>
        </tr>
      {/each}
    </tbody>
  </table>
{:else}
  <p class="banner">
    No ART baselines committed yet — most ART scenarios assert on FFT/spectrum properties rather
    than byte-exact PCM.
  </p>
{/if}

<h2>VRT — Visual Regression Tests</h2>
{#if data.vrtImplemented}
  <p>VRT harness present at <code>vrt/</code>. (Auto-detected at docs build.)</p>
{:else}
  <div class="banner">
    <strong>Status: planned, not yet implemented.</strong> The plan
    (<code>.myrobots/plans/testing-strategy.md</code>) calls for Playwright screenshot diffs
    across pinned Chromium / WebKit / Firefox + a fixed font set in CI. The harness directory
    <code>vrt/</code> does not exist yet; this section will populate with a baseline gallery
    once it does.
  </div>
{/if}

<h2>E2E — Playwright</h2>
<p>
  Headless Chromium, real Web Audio (worklets and all), against the actual SvelteKit app. Boots a
  Vite dev server (or <code>vite preview</code> when <code>E2E_USE_PREVIEW=1</code>). Lives under
  <code>e2e/tests/</code>; specs tagged <code>@smoke</code> double as the post-deploy live check
  on autotest.
</p>
<pre><code>flox activate -- task e2e          # full suite
flox activate -- task e2e:headed   # with the browser visible
flox activate -- task ci:smoke:live  # smoke vs autotest.patchtogether.live</code></pre>

<h3>Specs ({data.e2eSpecs.length})</h3>
<ul>
  {#each data.e2eSpecs as s (s)}
    <li><code>{s}</code></li>
  {/each}
</ul>

<h2>Chaos</h2>
<p>
  Single-user randomized intent fuzzer. Drives the canvas through 200+ random patches /
  mutations; checks invariants between each. Multi-user invariants land post-Stage B.
</p>
<pre><code>flox activate -- task chaos:run</code></pre>

<h2>CI shape</h2>
<p>
  The full gate runs in <code>.github/workflows/ci.yml</code> inside Flox so the toolchain (Node
  22, Faust 2.85.5, esbuild) matches local. Postgres 17 is a service container; the DB schema is
  applied before <code>task ci</code> runs.
</p>
