// e2e/vrt/workflow-rear-card.spec.ts
//
// VRT: the REAR CARD — the dock full-view's flip side (rear-card-spec.md).
// PINNED scenes bracket the range and pin the curation shapes:
//
//   rear-tidyVco — the BUSIEST prototype: the leading voice section + the five
//     face-page sections (oscillator authored, EG clusters, audio-rate `~`
//     ticks) + the OUTPUT zone with its collapsed stereo hole. The lane
//     auto-wire seats real plugs (endpoint chips) deterministically.
//   rear-vca — the SIMPLEST: the authored signal → gain-stage split and a
//     two-hole rail; pins the frame/hatch/footer at minimum density.
//
// P1 batch 2 adds the two rears the batch's most complex module pair needs —
// the axes tidyVco/vca do NOT already cover:
//
//   rear-dx7 — the batch's most complex FACE (4 pages, 10 ranked controls, a
//     preset selector + a file-input family) has the SIMPLEST possible rear:
//     note-source inputs and one output, ZERO per-param CV. It is the only
//     pinned scene where the whole field is ONE authored section with an
//     inline CLUSTER inside it (the mono PITCH CV + GATE legacy pair split out
//     of the poly bus) — a shape derivation cannot produce, on a card with no
//     CV sections at all to dilute it.
//   rear-sixstrum — the batch's genuinely busiest FIELD: an authored leading
//     section with TWO sub-header clusters (the strum triggers, the mute
//     gates), the derived per-param CV sections, and by far the widest
//     audio-rate `~` tick set on any pinned scene.
//
// ⚠ #1800 moved all four of these: one row grammar on both rails, sections as
// COLUMNS, and the faceplate body no longer forced to the front kit's 900px.
//
// Deterministic by construction: the rear card renders NO live glyphs and NO
// knobs — labels, recessed holes, domain rings and seated plugs only; the
// only animation (the carry pulse) never runs here (nothing is carried), and
// the boot style tag kills transitions anyway. Element-capture of the
// faceplate, workflow-shell-faces budgets.
//
// Baselines are authored by LINUX CI — one set, no {platform} segment (see
// vrt.config.ts). `task vrt:commit` dispatches the capture; a local macOS run
// is a smoke test, not a capture.
//
// ⚠⚠ THESE FOUR BASELINES ARE AUTHORED BUT NEVER COMPARED ON PR CI. Two facts
// compound, and neither is obvious from this file:
//
//   1. this spec is in `FULL_MATCH` only, NOT `STRICT_MATCH` (vrt.config.ts),
//      so the required `vrt-strict` context does not run it; and
//   2. the full-sweep `vrt` job — the informational lane that compared
//      everything outside the strict subset — was DELETED 2026-08-17. ci.yml
//      says it outright: "THIS IS NOW THE ONLY LANE THAT COMPARES A BASELINE …
//      What is gone is the COMPARISON of everything outside STRICT_VRT_MODULES."
//
// So a rear-card visual regression reddens NOTHING — not a required check, not
// an informational one. These PNGs are REVIEW MATERIAL, not a gate. Do not
// read a green PR as evidence that they still match the code. Closing the gap
// means widening `vrt-strict` to include these scenes, which is a CI wall-time
// decision, not a drive-by.
//
// ⚠ AND THE STALENESS IS NOT HYPOTHETICAL — it happened here, on #1800.
// `REAR_MAX_DIFF` is 1500 px against a ~305k px capture, so a change that
// re-flows a few LABELS sits UNDER tolerance and the comparison PASSES. At the
// time the capture ran `--update-snapshots=changed`, which only rewrites a
// snapshot whose comparison FAILS, so it rewrote NOTHING: a dispatch came back
// "4 passed / No VRT baseline changes — nothing to commit" over four baselines
// that genuinely no longer matched the CSS. The workaround was to `git rm` them
// first so the next dispatch wrote them as MISSING; all four were byte-different
// afterwards, which is what proved they had been stale.
//
// ✅ THE SECOND HALF OF THAT IS FIXED (2026-08-26): the capture runs
// `--update-snapshots=all`, which does not consult the baseline and rewrites on
// a BYTE difference, so a stale-but-passing baseline here IS now regenerated by
// an ordinary dispatch and the `git rm` step is gone. ⚠ The FIRST half stands
// unchanged and is what this note is really about: `REAR_MAX_DIFF` still means
// the ordinary comparison cannot SEE the drift, so nothing tells you a capture
// is due. Closing that is the widening decision above, not a flag.

import { test, expect, type Page } from '@playwright/test';
import { pinVrtFonts, awaitVrtFonts } from './_fonts';
import { pressFlipKey } from '../tests/_flip-key';

test.describe.configure({ mode: 'default' });

/** The pinned scenes — the module TYPES only.
 *
 *  ⚠ This table used to carry `ports` / `holes` / `stereoHoles` per scene, and
 *  every one of them was a HAND-TYPED POPULATION COUNT of a def's port list
 *  (CLAUDE.md P0). They are gone: the structural gate below reads the declared
 *  ports off the LIVE def (`window.__moduleSpecs`) and the collapsed pairs off
 *  the RENDERED DOM, and asserts the relation between them. That is strictly
 *  stronger — the old table could be edited to match a regression, and a def
 *  gaining a port made it stale without any gate noticing — and it removes the
 *  re-count tax on anyone who adds a jack to one of these four modules. */
const SCENES = ['tidyVco', 'vca', 'dx7', 'sixstrum'] as const;

/** Declared inputs + outputs for `type`, read off the live registry the page
 *  exposes — never restated here. */
async function declaredPortCount(page: Page, type: string): Promise<number> {
  return page.evaluate((t) => {
    const w = globalThis as unknown as {
      __moduleSpecs: Array<{ type: string; inputs: unknown[]; outputs: unknown[] }>;
    };
    const spec = w.__moduleSpecs.find((s) => s.type === t);
    if (!spec) throw new Error(`no module spec for ${t}`);
    return spec.inputs.length + spec.outputs.length;
  }, type);
}

/** Full-width faceplate element capture (workflow-shell-faces budget). */
const REAR_MAX_DIFF = 1500;

async function waitForHooks(page: Page): Promise<void> {
  await page.waitForFunction(
    () => {
      const w = globalThis as unknown as {
        __setSpawnFlowPos?: unknown;
        __spawnFromPalette?: unknown;
        __openDockFullView?: unknown;
      };
      return (
        typeof w.__setSpawnFlowPos === 'function' &&
        typeof w.__spawnFromPalette === 'function' &&
        typeof w.__openDockFullView === 'function'
      );
    },
    undefined,
    { timeout: 20_000 },
  );
}

/** Boot `?shell=1`, spawn `type` into lane 1 via the REAL palette-drop path
 *  (the lane auto-wire seats deterministic plugs on the rear), and return the
 *  member's node id — the workflow-shell-faces boot recipe. */
async function bootWithMember(page: Page, type: string): Promise<string> {
  await pinVrtFonts(page);
  await page.goto('/rack');
  await page.waitForLoadState('networkidle');
  await awaitVrtFonts(page);
  await waitForHooks(page);

  await page.evaluate((t) => {
    const w = globalThis as unknown as {
      __setSpawnFlowPos: (p: { x: number; y: number }) => void;
      __spawnFromPalette: (t: string) => void;
    };
    // x=30 lands inside narrowed column 1's band; y=4280 lands inside the
    // lane's PAINTED band (the drop hit-test is 2-D — a Y above the lanes is
    // free canvas and joins no lane).
    w.__setSpawnFlowPos({ x: 30, y: 4280 });
    w.__spawnFromPalette(t);
  }, type);
  await page.waitForFunction(() => {
    const w = globalThis as unknown as {
      __patch?: { nodes: Record<string, { data?: { columns?: Record<string, string[]> } } | undefined> };
    };
    return (w.__patch?.nodes['pinned-mixmstrs']?.data?.columns?.['1'] ?? []).length === 1;
  });
  const memberId = await page.evaluate(() => {
    const w = globalThis as unknown as {
      __patch: { nodes: Record<string, { data?: { columns?: Record<string, string[]> } } | undefined> };
    };
    return (w.__patch.nodes['pinned-mixmstrs']?.data?.columns?.['1'] ?? [])[0] ?? '';
  });
  expect(memberId, `${type}: the lane-1 member spawned`).not.toBe('');

  await page.addStyleTag({
    content:
      '.svelte-flow__minimap,.svelte-flow__controls,.svelte-flow__attribution,.minimap-toggle{display:none !important;}' +
      '*,*::before,*::after{animation:none !important;transition:none !important;}',
  });
  return memberId;
}

test.describe('VRT: rear card — the dock full-view flip side', () => {
  for (const type of SCENES) {
    test(`rear-${type}: the flip-side jack field matches baseline`, async ({ page }) => {
      const errors: string[] = [];
      page.on('pageerror', (e) => errors.push(e.message));

      const memberId = await bootWithMember(page, type);

      // Open the dock full-view (the same dockStore call the EXPAND pill
      // makes) and flip it with the bare-Tab rack-flip shortcut.
      await page.evaluate(
        (id) => (globalThis as unknown as { __openDockFullView: (id: string) => void }).__openDockFullView(id),
        memberId,
      );
      const faceplate = page.getByTestId('dock-full-view');
      await expect(faceplate).toBeVisible();
      await pressFlipKey(page);
      await expect(faceplate).toHaveAttribute('data-flipped', 'true');

      // Structural gate before the pixel pin: the field is up, every declared
      // port is addressed by exactly one hole, the control face is gone.
      const rear = faceplate.getByTestId('rear-card');
      await expect(rear).toBeVisible();
      // DERIVED on both sides: the declared ports come from the live def, the
      // collapsed pairs from the rendered DOM, and the rendered hole count must
      // be the difference. A dropped jack cannot hide inside the shortfall, and
      // nothing here is a literal anyone has to re-count.
      const ports = await declaredPortCount(page, type);
      const collapsed = await rear
        .locator('[data-testid="back-jack"][data-stereo-sibling]')
        .count();
      await expect(
        rear.locator('[data-testid="back-jack"]'),
        `${type}: ${ports} declared ports (live def) minus ${collapsed} collapsed pair(s) on the page`,
      ).toHaveCount(ports - collapsed);
      // …and every rendered hole sits in a section of its own direction, which
      // is the #1800 shape: two zones, one row grammar, nothing loose.
      await expect(
        rear.locator('[data-testid="rear-section"]').first(),
        `${type}: the field renders as section columns`,
      ).toBeVisible();
      const strays = await rear.evaluate((card) =>
        Array.from(card.querySelectorAll('[data-testid="back-jack"]'))
          .filter(
            (j) =>
              j.closest('[data-testid="rear-section"]')?.getAttribute('data-direction') !==
              j.getAttribute('data-direction'),
          )
          .map((j) => j.getAttribute('data-port-id')),
      );
      expect(strays, `${type}: holes filed into a section of the wrong direction`).toEqual([]);
      await expect(faceplate.getByTestId('faceplate-editor')).toBeHidden();
      // The lane auto-wire seats the member's plugs — deterministic chips.
      await expect(rear.locator('[data-testid="back-jack"][data-patched="true"]').first()).toBeVisible();

      await page.evaluate(
        () => new Promise<void>((r) => requestAnimationFrame(() => requestAnimationFrame(() => r()))),
      );
      await expect(faceplate).toHaveScreenshot(`rear-${type}.png`, {
        maxDiffPixels: REAR_MAX_DIFF,
      });

      expect(
        errors.filter((e) => !/getUserMedia|audio/i.test(e)),
        `pageerrors: ${errors.join(' | ')}`,
      ).toEqual([]);
    });
  }
});
