<script lang="ts">
  import IoDiagram from '$lib/docs/IoDiagram.svelte';

  let { data } = $props();
  const mod = $derived(data.mod);
</script>

<svelte:head>
  <title>{mod.label} · modules · patchtogether.live</title>
  <meta name="description" content={mod.description} />
</svelte:head>

<section class="hero">
  <h1>
    {mod.label}
    {#if mod.maxInstances === 1}
      <span class="tag singleton">singleton</span>
    {/if}
  </h1>
  <div class="sub">
    <code>{mod.type}</code> · {mod.category}
    {#if mod.schemaVersion !== undefined}
      · schema v{mod.schemaVersion}
    {/if}
  </div>
</section>

<p>{mod.description}</p>

{#if mod.docs?.explanation}
  <p class="authored-explanation" data-testid="docs-explanation">{mod.docs.explanation}</p>
{/if}

{#if data.guide}
  <a class="guide-callout" href={data.guide.href} data-testid="module-guide-link">
    <span class="guide-icon" aria-hidden="true">📖</span>
    <span class="guide-text">
      <strong>Full guide: {data.guide.title}</strong>
      <span class="guide-blurb">{data.guide.blurb}</span>
    </span>
    <span class="guide-arrow" aria-hidden="true">→</span>
  </a>
{/if}

{#if data.face}
  <!-- THE FACE — numbered device-face screenshot of the real rendered card
       (docs-overhaul §3b), generated by the VRT-annotated pipeline. Replaces
       the abstract IoDiagram as the primary visual. -->
  <h2>the face</h2>
  <div class="face-wrap" data-testid="module-face">
    <img
      class="face-img"
      src={data.face.src}
      alt={`Numbered control face for ${mod.label}`}
      loading="lazy"
    />
    {#if data.face.controls.length > 0}
      <table class="face-legend" data-testid="module-face-legend">
        <thead>
          <tr><th>#</th><th>control</th><th>kind</th></tr>
        </thead>
        <tbody>
          {#each data.face.controls as c (c.n)}
            <tr>
              <td class="legend-n">{c.n}</td>
              <td>{c.label}{#if c.units}&nbsp;<span class="units">({c.units})</span>{/if}</td>
              <td class="legend-kind">{c.kind}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </div>
{:else}
  <!-- Fallback: no numbered face generated yet → the abstract pin diagram. -->
  <div class="diagram-wrap" data-testid="module-diagram">
    <IoDiagram mod={mod} />
    <div class="port-counts">
      <span data-testid="input-count">{mod.inputs.length} inputs</span>
      ·
      <span data-testid="output-count">{mod.outputs.length} outputs</span>
      ·
      <span data-testid="param-count">{mod.params.length} params</span>
    </div>
  </div>
{/if}

<!-- INPUTS & OUTPUTS — AUTO-GENERATED from the enriched module def via
     io-explain (docs-overhaul §3c). The `explain` column is the single source
     of truth; it cannot drift from the def (the drift gate fails CI if any
     port lacks an explanation). -->
{#if mod.io.inputs.length > 0}
  <h2>inputs</h2>
  <table data-testid="io-inputs">
    <thead>
      <tr><th>id</th><th>cable</th><th>what it does</th></tr>
    </thead>
    <tbody>
      {#each mod.io.inputs as p (p.id)}
        <tr>
          <td><code>{p.id}</code></td>
          <td>{p.type}</td>
          <td>
            {#if mod.docs?.inputs?.[p.id]}
              {mod.docs.inputs[p.id]}
              <div class="io-explain">{p.explain}</div>
            {:else}{p.explain}{/if}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

{#if mod.io.outputs.length > 0}
  <h2>outputs</h2>
  <table data-testid="io-outputs">
    <thead>
      <tr><th>id</th><th>cable</th><th>what it does</th></tr>
    </thead>
    <tbody>
      {#each mod.io.outputs as p (p.id)}
        <tr>
          <td><code>{p.id}</code></td>
          <td>{p.type}</td>
          <td>
            {#if mod.docs?.outputs?.[p.id]}
              {mod.docs.outputs[p.id]}
              <div class="io-explain">{p.explain}</div>
            {:else}{p.explain}{/if}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

{#if mod.params.length > 0}
  <h2>params</h2>
  <table>
    <thead>
      <tr><th>id</th><th>label</th><th>range</th><th>default</th><th>curve</th></tr>
    </thead>
    <tbody>
      {#each mod.params as p (p.id)}
        <tr>
          <td><code>{p.id}</code></td>
          <td>{p.label}</td>
          <td>
            {p.min ?? '?'}..{p.max ?? '?'}{#if p.units}
              {p.units}{/if}
          </td>
          <td>{p.defaultValue ?? '—'}</td>
          <td>{p.curve}</td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

{#if mod.docs?.controls && Object.keys(mod.docs.controls).length > 0}
  <h2>controls</h2>
  <table data-testid="docs-controls">
    <thead>
      <tr><th>control</th><th>what it does</th></tr>
    </thead>
    <tbody>
      {#each Object.entries(mod.docs.controls) as [k, desc] (k)}
        <tr>
          <td><code>{k}</code></td>
          <td>{desc}</td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

<h2>source</h2>
<p>
  <a href={mod.sourceUrl} rel="noopener">{mod.file}</a> on GitHub.
</p>

<nav class="prev-next">
  {#if data.prev}
    <a href="/docs/modules/{data.prev.type}" class="prev">← {data.prev.label}</a>
  {:else}
    <span></span>
  {/if}
  <a href="/docs/modules" class="all">all modules</a>
  {#if data.next}
    <a href="/docs/modules/{data.next.type}" class="next">{data.next.label} →</a>
  {:else}
    <span></span>
  {/if}
</nav>

<style>
  .guide-callout {
    display: flex;
    align-items: center;
    gap: 0.85rem;
    margin: 1.25rem 0;
    padding: 0.9rem 1rem;
    border: 1px solid var(--doc-accent, #2bb6c8);
    border-left-width: 4px;
    border-radius: 6px;
    background: color-mix(in srgb, var(--doc-accent, #2bb6c8) 8%, transparent);
    text-decoration: none;
    color: inherit;
    transition: background 0.12s ease;
  }
  .guide-callout:hover {
    background: color-mix(in srgb, var(--doc-accent, #2bb6c8) 16%, transparent);
  }
  .guide-icon {
    font-size: 1.4rem;
    line-height: 1;
  }
  .guide-text {
    display: flex;
    flex-direction: column;
    gap: 2px;
    flex: 1;
  }
  .guide-blurb {
    color: var(--doc-fg-dim, #6e7a82);
    font-size: 0.86em;
  }
  .guide-arrow {
    font-size: 1.2rem;
    color: var(--doc-accent, #2bb6c8);
  }
  .authored-explanation {
    font-size: 1.02em;
    line-height: 1.55;
  }
  .io-explain {
    color: var(--doc-fg-dim, #6e7a82);
    font-size: 0.82em;
    margin-top: 2px;
  }
  .diagram-wrap {
    margin: 1.5rem 0;
  }
  .face-wrap {
    display: flex;
    flex-wrap: wrap;
    gap: 1.25rem;
    align-items: flex-start;
    margin: 1rem 0 1.5rem;
  }
  .face-img {
    max-width: min(100%, 480px);
    height: auto;
    border: 1px solid var(--doc-border-dim, #062b32);
    border-radius: 6px;
    background: #0a0a0a;
  }
  .face-legend {
    flex: 1;
    min-width: 220px;
    margin: 0;
  }
  .face-legend .legend-n {
    text-align: center;
    font-variant-numeric: tabular-nums;
    color: var(--doc-accent, #2bb6c8);
    font-weight: 700;
  }
  .face-legend .legend-kind,
  .face-legend .units {
    color: var(--doc-fg-dim, #6e7a82);
    font-size: 0.88em;
  }
  .port-counts {
    color: var(--doc-fg-dim, #6e7a82);
    font-size: 0.82em;
    text-align: center;
    margin-top: -4px;
  }
  .prev-next {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 1rem;
    margin: 3rem 0 0;
    padding-top: 1rem;
    border-top: 1px solid var(--doc-border-dim, #062b32);
    font-size: 0.86em;
  }
  .prev-next .all {
    color: var(--doc-fg-dim, #6e7a82);
  }
</style>
