// packages/web/src/lib/ui/workflow/face-migration-report.ts
//
// THE PROGRESS SURFACE for the face-migration inventory — the markdown the owner
// reads to watch the number move (docs/design/face-migration.generated.md).
//
// ⚠ IT IS GENERATED, and that is the whole point. The repo standard forbids a
// hand-typed population count; the exception the standard names is a GENERATED
// artifact reviewed as a diff on an accept loop. So the counts live HERE, as a
// pure function of (the inventory record × the live registry × STRICT_FACES),
// regenerated by `flox activate -- task face:inventory:accept` and pinned by a
// freshness gate. Nothing reads a number back out: no assertion anywhere takes
// a size from this file.
//
// DETERMINISM: no dates, no git, no environment. Every list is sorted by module
// type, so two regenerations are byte-identical and a diff means the migration
// actually moved.

import {
  FACE_MIGRATION_INVENTORY,
  MIGRATION_BLOCKERS,
  inventoryEntry,
  migrationBlockers,
  migrationDone,
  type FaceMigrationDisposition,
} from './face-migration-inventory';

/** One registered module, as the report needs it. */
export interface ReportModule {
  readonly type: string;
  readonly domain: string;
  /** STRICT_FACES membership — passed in, never re-derived here. */
  readonly faced: boolean;
}

const DISPOSITION_ORDER: readonly FaceMigrationDisposition[] = [
  'generic-face',
  'blocked',
  'bespoke-surface',
  'organizational-native',
];

const DISPOSITION_BLURB: Readonly<Record<FaceMigrationDisposition, string>> = {
  'generic-face': 'author a `face` and rank the controls — no new platform capability',
  blocked: 'would be a face today but for the named capability, and nothing else',
  'bespoke-surface': 'the primary interaction is not param-shaped — needs a purpose-built surface',
  'organizational-native': 'rack furniture; not a migration at all',
};

function table(rows: readonly (readonly string[])[], head: readonly string[]): string {
  const out = [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`];
  for (const r of rows) out.push(`| ${r.join(' | ')} |`);
  return out.join('\n');
}

/**
 * Render the generated progress artifact.
 *
 * PURE: same modules in, same markdown out. `modules` is the LIVE registry, so a
 * module added without an inventory entry shows up in the "unclassified" row
 * rather than silently vanishing — the same denial the gate makes fatal, said
 * once more where a human will read it.
 */
export function renderFaceMigrationReport(modules: readonly ReportModule[]): string {
  const sorted = [...modules].sort((a, b) => a.type.localeCompare(b.type));

  const byDisposition = new Map<FaceMigrationDisposition, ReportModule[]>();
  const unclassified: string[] = [];
  const done: string[] = [];
  const todo: string[] = [];
  for (const m of sorted) {
    const entry = inventoryEntry(m.type);
    if (!entry) {
      unclassified.push(m.type);
      continue;
    }
    const bucket = byDisposition.get(entry.disposition) ?? [];
    bucket.push(m);
    byDisposition.set(entry.disposition, bucket);
    if (migrationDone(entry, m.faced)) done.push(m.type);
    else if (entry.disposition !== 'organizational-native') todo.push(m.type);
  }

  const registered = new Set(sorted.map((m) => m.type));
  const orphaned = FACE_MIGRATION_INVENTORY.map((e) => e.type)
    .filter((t) => !registered.has(t))
    .sort();

  const lines: string[] = [];
  lines.push('<!-- GENERATED FILE — DO NOT EDIT.');
  lines.push('     Regenerate: `flox activate -- task face:inventory:accept`, then review the diff.');
  lines.push('     Source: packages/web/src/lib/ui/workflow/face-migration-inventory.ts × the live');
  lines.push('     module registry × STRICT_FACES. Pinned by face-migration-inventory.test.ts. -->');
  lines.push('');
  lines.push('# Face migration status (LEG-01)');
  lines.push('');
  lines.push(
    'Every registered module carries exactly one **disposition**: what kind of work its v2 ' +
      'surface needs. A module is **done** when it declares a `face` and is promoted into ' +
      '`STRICT_FACES` — read off the def, never recorded here.',
  );
  lines.push('');

  lines.push('## Where the fleet stands');
  lines.push('');
  lines.push(
    table(
      [
        ['registered modules', String(sorted.length)],
        ['done (faced + promoted)', String(done.length)],
        ['remaining (excludes organizational-native)', String(todo.length)],
        ['registered with NO disposition (must be zero)', String(unclassified.length)],
        ['inventory entries naming a dead def (must be zero)', String(orphaned.length)],
      ],
      ['', 'count'],
    ),
  );
  lines.push('');

  lines.push('## By disposition');
  lines.push('');
  const rows: string[][] = [];
  for (const d of DISPOSITION_ORDER) {
    const members = byDisposition.get(d) ?? [];
    const doneHere = members.filter((m) => m.faced).length;
    rows.push([
      `\`${d}\``,
      DISPOSITION_BLURB[d],
      String(members.length),
      d === 'generic-face' ? String(doneHere) : '—',
    ]);
  }
  lines.push(table(rows, ['disposition', 'what it means', 'modules', 'done']));
  lines.push('');

  lines.push('## What each blocker buys');
  lines.push('');
  const blockerRows: string[][] = [];
  for (const id of Object.keys(MIGRATION_BLOCKERS).sort()) {
    const users = sorted
      .map((m) => inventoryEntry(m.type))
      .filter((e): e is NonNullable<typeof e> => !!e)
      .filter((e) => (migrationBlockers(e) as readonly string[]).includes(id));
    blockerRows.push([`\`${id}\``, `#${MIGRATION_BLOCKERS[id]!.issue}`, String(users.length)]);
  }
  lines.push(table(blockerRows, ['blocker', 'issue', 'modules waiting']));
  lines.push('');

  for (const d of DISPOSITION_ORDER) {
    const members = byDisposition.get(d) ?? [];
    lines.push(`## \`${d}\``);
    lines.push('');
    lines.push(DISPOSITION_BLURB[d] + '.');
    lines.push('');
    if (members.length === 0) {
      lines.push('_none_');
      lines.push('');
      continue;
    }
    const memberRows = members.map((m) => {
      const entry = inventoryEntry(m.type)!;
      const blockers = migrationBlockers(entry);
      return [
        `\`${m.type}\``,
        m.domain,
        m.faced ? 'done' : '—',
        blockers.length ? blockers.map((b) => `\`${b}\``).join(' ') : '—',
      ];
    });
    lines.push(table(memberRows, ['module', 'domain', 'state', 'blockers']));
    lines.push('');
  }

  if (unclassified.length > 0) {
    lines.push('## ⚠ registered with NO disposition');
    lines.push('');
    lines.push(unclassified.map((t) => `\`${t}\``).join(', '));
    lines.push('');
  }
  if (orphaned.length > 0) {
    lines.push('## ⚠ inventory entries naming a def that no longer exists');
    lines.push('');
    lines.push(orphaned.map((t) => `\`${t}\``).join(', '));
    lines.push('');
  }

  return lines.join('\n');
}
